service: # service type can only be ClusterIP
  type: ClusterIP


ingress: # ingress should be disabled
  enable: false


config: # containers configs
  restartPolicy: Never
  imagePullPolicy: IfNotPresent


# list of your jobs goes here
jobs: [] # remove this
  # list your jobs like the example bellow
  # - name: pull-codes # job name
  #   cron: "* 1 * * * *" # cron (cronjob scheduling)
  #   image: gitPuller:v0.1.0 # docker image
  #   env: # environment variables
  #   - name: ENV_VAR
  #     valueFrom:
  #       configMapKeyRef:
  #         name: special-config
  #         key: special.how
  #
  # another example
  # - name: push-changes
  #   cron: "5 * * * * *"
  #   image: gitPusher:v2.1.0
