{{- $restartPolicy := .Values.config.restartPolicy -}}
{{- $imagePullPolicy := .Values.config.imagePullPolicy -}}
{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $job.name }}-cronjob
  labels:
    app: cronjob
    type: cron
spec:
  schedule: {{ $job.cron | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ $job.name }}-container
            image: {{ $job.image }}
            imagePullPolicy: {{ $imagePullPolicy }}
            # command:
            #   {{- range $job.commands }}
            #     - {{ . }}
            #   {{- end}}
            restartPolicy: {{ $restartPolicy }}
{{- end -}}